version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # ホストの3000番ポートをコンテナの80番ポートにマッピング
    volumes:
      - .:/app  # ソースコードをコンテナ内にマウント